# Generated by Django 2.1.2 on 2019-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmiddleware', '0002_lawyer_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='admission_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
