# Generated by Django 2.1.2 on 2019-02-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmiddleware', '0003_auto_20190202_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='cases',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
